### PR TITLE
Feature: Overwrite warning

### PR DESCRIPTION
**Pull request by jmmendivil**
Ask the user for overwrite confirmation when a component file already exists in build path.

Uses Bulma Modal and Message components

image

Related to #21

### CODE REVIEW

**Comment by sethdavis512** [comment]
Hey @jmmendivil - Thanks for the contribution. Would you mind pulling the latest from `development`?

**Comment by jmmendivil** [comment]
It's updated with 90da83b but maybe I'm missing something, can you point me in the right direction?

**Comment by sethdavis512** [comment]
@jmmendivil I think all you should have to do is set my repo to your upstream, then do a git pull upstream origin development.

1) https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
2) https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by jmmendivil** [comment]
Thank you, @sethdavis512.

Updated

**Comment by sethdavis512** [comment]
I think you fork needs some more adjustments. If your fork is up to date - I shouldn't be seeing any of my previous commits, only your changes. @jvmoreira was able to update his on this PR: https://github.com/sethdavis512/pseudopia-app/pull/24

Could you give it another try?

**Comment by jmmendivil** [comment]
I suppose it's not FF, I will create a new fork and send the PR again

**Pull request closed without merging**
